weekly graph
joncolon/inContaq pull request #6
Opened 2017-03-12 19:08 UTC by jdlopez114

This is actually weekly graph and not monthly like the branch name.

2017-03-13 02:53 UTC, robertjli requested changes

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/contactlist/fragments/ContactStatsFragment.java
> +//        WeeklyGraph weeklyGraph = new WeeklyGraph(getContext(), lineGraph, lstSms);
Why is this commented out?

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +        getHigehstValueForYaxis();
getHighest

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +    private ArrayList<Sms> lstSms;
listSms

Don't worry, we have plenty of vowels ;)

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +        for (Map.Entry<Integer, Integer> entry : numberOfTexts.entrySet()) {
you can use numberOfTexts.values() if all you want are the values

https://docs.oracle.com/javase/7/docs/api/java/util/TreeMap.html#values()

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +    private float[] setValues(TreeMap<Integer, Integer> numberOfTexts) {
It seems like the only purpose of this function is to convert all the values from ints to floats?

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +        TreeMap<Integer, Integer> monthlyReceived = setUpDailyTextMap();
Should this be weeklyReceived?

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +            return highestValue = (int) getRound(maxSent);
You should either return the number or set it to highestValue. You don't need to do both.

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +    private long getRound(int input) {
Just return an int so you don't have to cast it later?

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +                maxValue = Math.round(inputArray[i]);
Either maxValue should be an int or you don't need to round. Just round at the end.

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +        LineSet dataSet = new LineSet(xAxisLabels, receivedValues);
Name this better.

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +        LineSet dataset = new LineSet(xAxisLabels, sentValues);
DEFINITELY name this better. `dataSet` and `dataset`? Really? lol

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +        dataset.setColor(parseColor("#b01cff"))
Use color variables that you set earlier?

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +        setHighestValueTo100();
If this crashes, then your previous setHighestValue function did something wrong...

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklyReceived.java
> +        super.onPostExecute(ret);
If all you do is call the superclass method, you don't need to override it.

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklyReceived.java
> +        weeklyTexts = params[0].weeklyTexts;
Why do you set weeklyTexts here? You overwrite it with your next call to getSmsStats()

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklyReceived.java
> +    private TreeMap<Integer, Integer> getMonthlyTexts(ArrayList<String> list) {
getWeeklyTexts()?

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklyReceived.java
> +            if (list.get(i).getType().equals("1")) {
"1" shouldn't be hardcoded - set it as a variable somewhere

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklyReceived.java
> +            DateTime juDate = new DateTime(lg);
what is juDate?

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklyReceived.java
> +            if (weeklyTexts.containsKey(month)) {
what if it doesn't contain the month?

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklyReceived.java
> +            int month = juDate.getMonthOfYear();
Should this be day of week?

2017-03-13 02:53 UTC, robertjli commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklySent.java
> +package nyc.c4q.jonathancolon.inContaq.utlities.sms.weekly;
Same comments on this file as WeeklyReceived.java

2017-03-15 00:21 UTC, robertjli commented
ping! any updates on these?

2017-03-15 00:25 UTC, joncolon commented
The intention is there, once major bugs are cleared

2017-03-15 00:26 UTC, robertjli commented
Cool, feel free to update this PR whenever. Just wanted to make sure you guys didn't lose this one

2017-03-15 02:22 UTC, joncolon commented
Actually you're totally right. I didn't even realize this wasn't my branch. I'm going to go through it now.

2017-03-15 04:48 UTC, abassawo commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/MonthlyGraph.java
> +                context.getString(R.string.dec)
Can also represent as string array in resources.

2017-03-15 04:48 UTC, abassawo commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +    private float[] setValues(TreeMap<Integer, Integer> numberOfTexts) {
yea you could try doing something like getDailyReceived(listSms).values().toArray(); Also setValues looks like it's really a getter method.

2017-03-15 04:48 UTC, abassawo commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +        TreeMap<Integer, Integer> monthlyReceived = setUpDailyTextMap();
any reason for the TreeMap vs any other map?

2017-03-15 04:48 UTC, abassawo commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +            ret[i] = iterator.next().intValue();
Do we need an iterator and iterator.next() if we're just looping from 0 to the length of ret, which is same length as floats?

2017-03-15 04:48 UTC, abassawo commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklyReceived.java
> +        weeklyTexts = getMonthlyTexts(receivedSms);
which one is it?

2017-03-15 04:48 UTC, abassawo commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklyReceived.java
> +            long lg = Long.parseLong(list.get(i));
better name for lg. what does this represent?

2017-03-15 04:48 UTC, abassawo commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklySent.java
> +        weeklyTexts = params[0].weeklyTexts;
this looks like it doesn't belong in the doInBackground...not sure though. why is this being changed in doInBackground

2017-03-15 04:48 UTC, abassawo commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklySent.java
> +        super.onPostExecute(ret);
what else should happen after the background work is executed?

2017-03-15 04:48 UTC, abassawo commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/sms/weekly/WeeklySent.java
> +        ArrayList<String> sentSms = new ArrayList<>();
List<String> sentSms = new ArrayList<>(); 
get in the habit of declaring by interface.

2017-03-18 00:05 UTC, hyunjkim commented on app/src/main/java/nyc/c4q/jonathancolon/inContaq/utlities/graphs/WeeklyGraph.java
> +        TreeMap<Integer, Integer> monthlyReceived = setUpDailyTextMap();
Yes, Jon looked up that TreeMaps can sort unlike other maps. He left a comment there, but I deleted it. Should we keep the comments there?

2017-03-20 20:28 UTC, merged